# Generated by Django 4.2.19 on 2025-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=0, max_length=64, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'owner')},
        ),
    ]
