# Generated by Django 4.2.19 on 2025-04-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('credit_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExpensesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
            ],
            options={
                'verbose_name': 'Категория трат',
                'verbose_name_plural': 'Категории трат',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
            ],
            options={
                'verbose_name': 'Категория дохода',
                'verbose_name_plural': 'Категории доходов',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Текущий остаток')),
                ('is_keeping', models.BooleanField(default=False, verbose_name='Накопительный')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
            ],
            options={
                'verbose_name': 'Cчёт',
                'verbose_name_plural': 'Cчёта',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransactionsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('aim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aim_sourse', to='accaunting.wallet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trans_sourse', to='accaunting.wallet')),
            ],
            options={
                'verbose_name': 'История переводов',
                'verbose_name_plural': 'История переводов',
            },
        ),
        migrations.CreateModel(
            name='IncomeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accaunting.incomecategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accaunting.wallet')),
            ],
            options={
                'verbose_name': 'История доходов',
                'verbose_name_plural': 'История доходов',
            },
        ),
        migrations.CreateModel(
            name='ExpensesSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accaunting.expensescategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
            ],
            options={
                'verbose_name': 'Подкатегория трат',
                'verbose_name_plural': 'Подкатегории трат',
                'unique_together': {('category', 'name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ExpensesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accaunting.expensescategory', verbose_name='Категория')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accaunting.expensessubcategory', verbose_name='Подкатегория')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accaunting.wallet', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'История трат',
                'verbose_name_plural': 'История трат',
            },
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Остаток')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accaunting.credit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
            ],
            options={
                'verbose_name': 'История оплаты кредитов',
                'verbose_name_plural': 'История оплаты кредитов',
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accaunting.expensescategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.project')),
            ],
            options={
                'verbose_name': 'План расходов',
                'verbose_name_plural': 'Планы расходов',
                'unique_together': {('year', 'month', 'category', 'project')},
            },
        ),
    ]
